### ISSUE TITLE
Plans to implement hybrid assembly?

### ISSUE THREAD

**Issue by microbemarsh** [ablab/metaGT#1]
Hi I was just wondering if you plan to add a long read component to metaGT? I know you mentioned in the [BMC Bioinformatics paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03614-2) from 2020 that hybrid assembly can be beneficial when assembling transcriptomes. Just a thought and I look forward to using this tool regardless!

**Comment by andrewprzh** [comment]
Hi @microbemarsh 

Thank you for the suggestion! Since MetaGT is based on metaSPAdes and rnaSPAdes, which both support hybrid assembly it should be doable. Will try to do in the nearest future. 

So far you can perform hybrid assembly separately and feed the contigs to MetaGT (less convinient, but can be used as urgrent workaround).

Best
Andrey
